### ISSUE TITLE
status and possibilities

### ISSUE THREAD

**Issue by obastemur** [andrewlow/v8ppc#121]
Hi!

I've stumbled into this project while I was planning the environment for jxcore powerpc build support. jxcore is a node.js fork/distro with multiple javascript engines (v8, sm) and additional features. Since we do have a recent SpiderMonkey in place, I beleive we wouldn't have much issue to run node apps on powerpc using jxcore.

On the other hand, we might consider a power-pc boosted version of v8 but I have some questions;

- Till what point you are expecting to maintain this project ?
- Any support, possibility of merge from V8 side ?
- Status of stability ?

Thanks!

**Comment by mdawsonibm** [comment]
We are currently contributing the ppc port back to the google repositories.  You can see here that there are buildbots for simulated PPC here:  http://build.chromium.org/p/client.v8/console

The main things that have not be contributed back yet are optimizations/features guarded by one of:

'V8_PPC_TAGGING_OPT', # optimization pending contribution
'V8_PPC_SIMULATOR', # feature pending contribution
'V8_PPC_CONSTANT_POOL_OPT', # feature pending contribution
'V8_PPC_CACHE_LINE_SIZE_OPT', # feature pending contribution

and we are working with the google team to get these accepted.  

I'd be interested in learning more about what you are doing.  I'll take a look at jxcore and maybe we can get in touch directly

**Comment by obastemur** [comment]
Indeed it looks really promising. I do have couple of quick questions. 

Which v8 version / interface is supported right now ? AFAIK IBM BlueMix offers node 0.10.x hosting on PPCs. In the mean time there is a back port. I'm a bit confused. 

Indeed I'm more than interested to get more details and make jxcore running on ppcs. We do already run node apps on Android, iOS, (and hopefully Windows ARM). 

You can reach me from obastemur [/at/] nubisa DOT com for further contact details.

Thanks!

**Comment by mdawsonibm** [comment]
We can only contribute code back to google repositories in the "bleeding edge" so that is where the code has been contributed back.  For our IBM Node 0.10.X and 0.12.X (soon)  deliveries we have stable versions of 3.14 and 3.28 which are maintained in branches in the v8ppc (this repo) and v8z repositories.

Once I have a chance to read up a bit on jxcore I'll ping you through email.

**Comment by obastemur** [comment]
Looking forward to that. BTW; I would like to give 3.14 a shot, there are three branches for 3.14, which one is I should be testing?

**Comment by mdawsonibm** [comment]
I think you would want to pull/build using this tag 

https://github.com/andrewlow/v8ppc/releases/tag/export-3.14-to-node-2014-12-22

**Comment by mhdawson** [comment]
Is it ok if we close this issue ?
