### ISSUE TITLE
gclient issues

### ISSUE THREAD

**Issue by daryltucker** [andrewlow/v8ppc#122]
Is `gclient` truly required?  Am I missing something here?

### Without `gclient`

    Fetching external item into 'testing/gmock/gtest'
    Checked out external at revision 692.

    Checked out revision 485.
    # The spec is a copy of the hooks in v8's DEPS file.
    gclient sync -r fb782d4369d5ae04f17a2fceef7de5a63e50f07b --spec="solutions = [{u'managed': False, u'name': u'buildtools', u'url': u'https://chromium.googlesource.com/chromium/buildtools.git', u'custom_deps': {}, u'custom_hooks': [{u'name': u'clang_format_win',u'pattern': u'.',u'action': [u'download_from_google_storage',u'--no_resume',u'--platform=win32',u'--no_auth',u'--bucket',u'chromium-clang-format',u'-s',u'buildtools/win/clang-format.exe.sha1']},{u'name': u'clang_format_mac',u'pattern': u'.',u'action': [u'download_from_google_storage',u'--no_resume',u'--platform=darwin',u'--no_auth',u'--bucket',u'chromium-clang-format',u'-s',u'buildtools/mac/clang-format.sha1']},{u'name': u'clang_format_linux',u'pattern': u'.',u'action': [u'download_from_google_storage',u'--no_resume',u'--platform=linux*',u'--no_auth',u'--bucket',u'chromium-clang-format',u'-s',u'buildtools/linux64/clang-format.sha1']}],u'deps_file': u'.DEPS.git', u'safesync_url': u''}]"
    /bin/sh: 1: gclient: not found
    make: *** [dependencies] Error 127

### With `gclient`

    Checked out revision 485.
    # The spec is a copy of the hooks in v8's DEPS file.
    gclient sync -r fb782d4369d5ae04f17a2fceef7de5a63e50f07b --spec="solutions = [{u'managed': False, u'name': u'buildtools', u'url': u'https://chromium.googlesource.com/chromium/buildtools.git', u'custom_deps': {}, u'custom_hooks': [{u'name': u'clang_format_win',u'pattern': u'.',u'action': [u'download_from_google_storage',u'--no_resume',u'--platform=win32',u'--no_auth',u'--bucket',u'chromium-clang-format',u'-s',u'buildtools/win/clang-format.exe.sha1']},{u'name': u'clang_format_mac',u'pattern': u'.',u'action': [u'download_from_google_storage',u'--no_resume',u'--platform=darwin',u'--no_auth',u'--bucket',u'chromium-clang-format',u'-s',u'buildtools/mac/clang-format.sha1']},{u'name': u'clang_format_linux',u'pattern': u'.',u'action': [u'download_from_google_storage',u'--no_resume',u'--platform=linux*',u'--no_auth',u'--bucket',u'chromium-clang-format',u'-s',u'buildtools/linux64/clang-format.sha1']}],u'deps_file': u'.DEPS.git', u'safesync_url': u''}]"
    Syncing projects:  66% (2/3), done.                          

    ________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s buildtools/win/clang-format.exe.sha1' in '.'
    Traceback (most recent call last):
      File "/usr/local/bin/gclient", line 10, in <module>
        sys.exit(gclient.Main(sys.argv[1:]))
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 2000, in Main
        return dispatcher.execute(OptionParser(), argv)
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/subcommand.py", line 245, in execute
        return command(parser, args[1:])
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 1778, in CMDsync
        ret = client.RunOnDeps('update', args)
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 1305, in RunOnDeps
        self.RunHooksRecursively(self._options)
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient.py", line 850, in RunHooksRecursively
        hook, cwd=self.root.root_dir, always=True)
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_utils.py", line 281, in CheckCallAndFilterAndHeader
        return CheckCallAndFilter(args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/gclient_utils.py", line 476, in CheckCallAndFilter
        **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/depot_tools/subprocess2.py", line 253, in __init__
        % (str(e), kwargs.get('cwd'), args[0]))
    OSError: Execution failed with error: [Errno 2] No such file or directory.
    Check that . or download_from_google_storage exist and have execution permission.
    make: *** [dependencies] Error 1

### System Information

    Linux 3.3.8 #1 SMP Tue Jun 19 18:03:48 CDT 2012 ppc64 GNU/Linux

[export-3.28-to-node-2015-03-27](https://github.com/andrewlow/v8ppc/releases/tag/export-3.28-to-node-2015-03-27)

**Comment by daryltucker** [comment]
Well, I can say that following [these instructions](https://www.chromium.org/developers/how-tos/install-depot-tools) will prevent this issue.

I had previously installed `gclient` via `pip`, which does not work.

I could have sworn I just compiled this last week without `gclient`, however.  Am I going crazy?

**Comment by mtbrandy** [comment]
I guess you resolved this.  FYI, for this version (3.28), you can also get by with just 'make dependencies'.
