### ISSUE TITLE
Links to build status in README.md are not ava.

### ISSUE THREAD

**Issue by allomov** [andrewlow/v8ppc#123]
Hey, all.

I've just found out that links to build status images are not available:

![image](https://www.evernote.com/shard/s108/sh/3a08d662-382c-4185-8a93-85f2ffb54244/750000f2ebc4a38d/res/cb2bdb73-3677-4425-bf72-fac64779d84b/skitch.png?resizeSmall&width=832)

**Comment by mhdawson** [comment]
Thanks I'll take a look into that.

**Comment by mhdawson** [comment]
Restarted jenkins and links show up again in the readme
