### ISSUE TITLE
fetch v8 fails on OSX 10.4 ppc7450

### ISSUE THREAD

**Issue by lisamcho** [andrewlow/v8ppc#124]
I installed the depot_tools, then I ran fetch v8, and I got the following error:

Running: gclient sync --with_branch_heads

curl: (35) error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm
v8/tools/clang/scripts/update.sh: line 342: svn: command not found
v8/tools/clang/scripts/update.sh: line 346: svn: command not found
Error: Command '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py --if-needed' returned non-zero exit status 127 in /Users/lmcho
Traceback (most recent call last):
  File "/Users/lmcho/depot_tools/fetch.py", line 345, in <module>
    sys.exit(main())
  File "/Users/lmcho/depot_tools/fetch.py", line 340, in main
    return run(options, spec, root)
  File "/Users/lmcho/depot_tools/fetch.py", line 334, in run
    return checkout.init()
  File "/Users/lmcho/depot_tools/fetch.py", line 142, in init
    self.run_gclient(*sync_cmd)
  File "/Users/lmcho/depot_tools/fetch.py", line 76, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/Users/lmcho/depot_tools/fetch.py", line 66, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 2

If I try to run gclient sync, i get...

Trying to download prebuilt clang

curl: (35) error:0D0890A1:asn1 encoding routines:ASN1_verify:unknown message digest algorithm
Did not find prebuilt clang 247874-1, building
Reverting previously patched files
Remove the Clang tools shim dir
Getting LLVM r247874 in v8/tools/clang/scripts/../../../third_party/llvm
v8/tools/clang/scripts/update.sh: line 342: svn: command not found
Checkout failed, retrying
v8/tools/clang/scripts/update.sh: line 346: svn: command not found
Error: Command '/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py --if-needed' returned non-zero exit status 127 in /Users/lmcho

**Comment by mhdawson** [comment]
Are you looking to compile v8 for ppc OSX ? If so,  that not supported, see discussion here:
https://github.com/andrewlow/v8ppc/issues/114
In particular the last comment. 

We build ppc for pLinux and AIX at this point.

**Comment by lisamcho** [comment]
Yes, sorry I missed that. That is exactly what I am trying to do. Thanks for letting me know!

**Comment by mhdawson** [comment]
I think this is resolved so I'll close.  Please let me know if you don't agree and I'll re-open
