### ISSUE TITLE
PPC64 mmap

### ISSUE THREAD

**Issue by edelsohn** [andrewlow/v8ppc#88]
In posix-platform.cc, OS::GetRandomMmapAddr() needs to generate a 64 bit address for PPC64 Linux and PPC64 AIX, following the code for X64.

-#ifdef V8_TARGET_ARCH_X64
+#if defined(V8_TARGET_ARCH_X64) || defined(V8_TARGET_ARCH_PPC64)

**Comment by mtbrandy** [comment]
Cleaning up old issues.  This is resolved.
